server:
  port: 8081

spring:
  application:
    name: ai-powered-customer-support-platform

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          time_zone: UTC

    open-in-view: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO

openai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-5-mini
  base-url: https://api.openai.com/v1

ollama:
  base-url: ${OLLAMA_BASE_URL}
  model: ${OLLAMA_MODEL}